# Generated by Django 2.2.5 on 2019-10-12 03:22

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название проекта')),
                ('main_image', models.ImageField(upload_to='Project_img', verbose_name='Главное изображение Проекта')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10, null=True, verbose_name='Географическая широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, null=True, verbose_name='Географическая длина')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текс на главной странице')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('projects', 'Проекты'), ('contacts', 'Контакты'), ('storage', 'Облачное хранилище'), ('requisites', 'Реквизиты')], max_length=50, verbose_name='Тип плитки')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок плитки (отображается при наведение на нее во всплывающем)')),
                ('main_image', models.ImageField(upload_to='Tile_img', verbose_name='Главное изображение плитки')),
                ('description', models.CharField(max_length=130, verbose_name='Описание плитки')),
            ],
            options={
                'verbose_name': 'Плитка',
                'verbose_name_plural': 'Плитки',
            },
        ),
    ]
