# Generated by Django 2.2.5 on 2019-10-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='is_availabled',
            field=models.BooleanField(default=True, verbose_name='Активна ли плитка'),
        ),
    ]
