# Generated by Django 2.2.5 on 2019-10-13 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191013_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Тема для обращения в обратной связи',
                'verbose_name_plural': 'Темы для обращения в обратной связи',
            },
        ),
        migrations.RemoveField(
            model_name='siteconf',
            name='topic',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Topic', verbose_name='Тема сообщения, будет выбираться и настроек сайта'),
        ),
    ]
