# Generated by Django 2.2.5 on 2019-10-14 01:59

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_project_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tile', to='core.Tile', verbose_name='Плитка к которой относится'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание на главной странице'),
        ),
    ]
